#!/usr/bin/env sh

# First get a list of directories at the top leve only and store the result
LISTING=`find . -maxdepth 1 -type d -exec echo {} \;`

# Split the above results into an array of directory names
files=$(echo $LISTING | tr " " "\n")

# Loop over each directory
for file in $files
do
	# Skip the current directory "."
	if [ "$file" != "." ]; then
		# If there is an AndroidManifest.xml file then it is a react-native CLI based project.  So look at it, if not skip it it was an expo project.
		if [ -f "$file/android/app/src/main/AndroidManifest.xml" ]; then
			# Grab the package name from the manifest file.
			LINE=`grep "package" $file/android/app/src/main/AndroidManifest.xml`
			
			# Grab what is between quotes and store the result.
			# echo $LINE | awk -F '"' '{print $2}'
			PACKAGE=`echo $LINE | cut -d'"' -f2`

			# Look for the package installed on device
			FOUND=`adb shell pm list packages $PACKAGE`
			if [ "$FOUND" != "" ]; then
				adb uninstall $PACKAGE
			fi
		fi
	fi
done
